[package]
name = "boost_align"
description = "Boost C++ library boost_align packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_align"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_align"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_core = { version = "0.1.0", path = "../boost_core" }
boost_static_assert = { version = "0.1.0", path = "../boost_static_assert" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
